import type { Metadata } from "next";
import { Inter, Vollkorn_SC } from "next/font/google";
import "./globals.css";

const vollkornSC = Vollkorn_SC({
  weight: ['400', '700', '900'], // Spécifiez les poids souhaités
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
     <body className={vollkornSC.className}>{children}</body>
      
    
    </html>
  );
}
